# Title: Data Preparation
# Description: The goal of this script is to create a csv data file that will contain all the required variables used in the data visualization phase.
# Inputs: The five data CSV files (one for each player) and the stacked csv file.
# Outputs: The summaries of each of the five data csv files and the stacked csv file.
library(stringr)
library(dplyr)
col_types = c("character", "character", "integer", "integer", "integer", "integer", "factor","character","factor","integer","character", "integer", "integer")
curry <- read.csv("../data/stephen-curry.csv", stringsAsFactors = F, colClasses = col_types)
iguodala <- read.csv("../data/andre-iguodala.csv", stringsAsFactors = F, colClasses = col_types)
green <- read.csv("../data/draymond-green.csv", stringsAsFactors = F, colClasses = col_types)
durant <- read.csv("../data/kevin-durant.csv", stringsAsFactors = F, colClasses = col_types)
thompson <- read.csv("../data/klay-thompson.csv", stringsAsFactors = F, colClasses = col_types)

curry <- mutate(curry, name = "Stephen Curry")
iguodala <- mutate(iguodala, name = "Andre Iguodala")
green <- mutate(green, name = "Graymond Green")
durant <- mutate(durant, name = "Kevin Durant")
thompson <- mutate(thompson, name = "Klay Thompson")

curry$shot_made_flag <- str_replace(curry$shot_made_flag, "n", "shot_no")
curry$shot_made_flag <- str_replace(curry$shot_made_flag, "y", "shot_yes")
iguodala$shot_made_flag <- str_replace(iguodala$shot_made_flag, "n", "shot_no")
iguodala$shot_made_flag <- str_replace(iguodala$shot_made_flag, "y", "shot_yes")
green$shot_made_flag <- str_replace(green$shot_made_flag, "n", "shot_no")
green$shot_made_flag <- str_replace(green$shot_made_flag, "y", "shot_yes")
durant$shot_made_flag <- str_replace(durant$shot_made_flag, "n", "shot_no")
durant$shot_made_flag <- str_replace(durant$shot_made_flag, "y", "shot_yes")
thompson$shot_made_flag <- str_replace(thompson$shot_made_flag, "n", "shot_no")
thompson$shot_made_flag <- str_replace(thompson$shot_made_flag, "y", "shot_yes")

curry <- mutate(curry, minute = (period - 1)*12 + 12 - minutes_remaining)
iguodala <- mutate(iguodala, minute = (period - 1)*12 + 12 - minutes_remaining)
green <- mutate(green, minute = (period - 1)*12 + 12 - minutes_remaining)
durant <- mutate(durant, minute = (period - 1)*12 + 12 - minutes_remaining)
thompson <- mutate(thompson, minute = (period - 1)*12 + 12 - minutes_remaining)

sink(file = "../output/stephen-curry-summary.txt")
summary(curry)
sink()
sink(file = "../output/andre-iguodala-summary.txt")
summary(iguodala)
sink()
sink(file = "../output/graymond-green-summary.txt")
summary(green)
sink()
sink(file = "../output/kevin-durant-summary.txt")
summary(durant)
sink()
sink(file = "../output/klay-thompson-summary.txt")
summary(thompson)
sink()

stacked <- rbind(curry,iguodala,green,durant,thompson)
write.csv(stacked, file = "../data/shots-data.csv")
sink(file = "../output/shots-data-summary.txt")
summary(stacked)
sink()
